# -*- coding: utf-8 -*-
"""score

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jhU70OJHIV8xZWKUgtJyhHaxVVCOFXQO
"""

score=input().split()
countF=0
total=0
min,max=int(score[0]),int(score[0])
for i in score:
  total=total+int(i)
  
  if int(i)<60:
    countF+=1
  if int(i)>max:
    max=int(i)
  if int(i)<min:
    min=int(i)
average=total/len(score)
print("平均:",average)
print("不及格人數:",countF)
print("min: ",min)
print("max: ",max)
